version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      DATABASE_URL: postgis://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # Call via sh to bypass CRLF issues
    command: ["sh","-lc","/app/entrypoint.sh"]

  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file: .env
    ports:
      - "5173:5173"
    # Remove bind mount to avoid hiding node_modules; add it later if you need hot-reload
    # volumes:
    #   - ./frontend:/app
    stdin_open: true
    tty: true

  nginx:
    build: ./nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    
volumes:
  pgdata:
